#! /bin/sh

sxhkd &
wmname fall &
picom &
$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/.wallpaper/light-japan.jpg &
wal -f base16-eighties -R &
xdo lower -N "Polybar" &
bspc rule -a polybar sticky=on &
bspc config top_padding 15 &
xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root) &
bspc rule -a '*:zathura' state=tiled 
bspc rule -a Zathura state=tiled

#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP1 -n 1 -d 1 2 3 4 5
bspc monitor eDP1 -n 2 -d 6 7 8 9
bspc config border_width         1
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
