# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#2d2d2d'
foreground='#d3d0c8'
cursor='#d3d0c8'

# Colors
color0='#2d2d2d'
color1='#f2777a'
color2='#99cc99'
color3='#ffcc66'
color4='#6699cc'
color5='#cc99cc'
color6='#66cccc'
color7='#d3d0c8'
color8='#747369'
color9='#f2777a'
color10='#99cc99'
color11='#ffcc66'
color12='#6699cc'
color13='#cc99cc'
color14='#66cccc'
color15='#f2f0ec'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
